name: Delete old releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Related: https://github.com/actions/checkout/issues/1471
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - run: |
          git tag --sort=-v:refname
          git tag --sort=-v:refname | grep nightly- | tail -n+2 | tail -n 1
          
          tags_to_delete=$(git tag --sort=-v:refname | grep nightly- | tail -n+2 | tail -n 1)
          echo "Will delete ${tags_to_delete[*]}"
          for tag_to_delete in "${tags_to_delete[@]}"
          do
             echo "Deleting $tag_to_delete"
             git push -v --delete origin "$tag_to_delete"
          done
