name: Delete old releases

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - run: |
          git tag --sort=-v:refname | grep nightly- | tail -n+2 | tail -n 1
          
          tags_to_delete=$(git tag --sort=-v:refname | grep nightly- | tail -n+2 | tail -n 1)
          echo "Will delete ${tags_to_delete[*]}"
          for tag_to_delete in "${tags_to_delete[@]}"
          do
             echo "Deleting $tag_to_delete"
             git push -v --delete origin "$tag_to_delete"
          done
